### PR TITLE
Fix: Do not ignore field values introduced by the user

### PR DESCRIPTION
**Pull request by coalman321**
This PR reverts a commit that removed code integral to changing the published values. This change affects versions 1.1.1 and forward.

### CODE REVIEW

**Comment by ShotaAk** [comment]
I am looking forward to seeing this change merged.
Are there no reviewers?

**Comment by coalman321** [comment]
@ivanpauno @jacobperron Could someone look this over and get it merged or create a fix with the intended way? In its current state, the lack of the ability to publish anything from the publisher tool makes it a bit useless.

**Comment by ivanpauno** [comment]
I will take a look.
@coalman321 could you share a minimal example to reproduce the issue?

**Comment by ivanpauno** [comment]
Ah sorry, I see https://github.com/ros-visualization/rqt_publisher/issues/27

**Comment by ivanpauno** [comment]
Sorry, this was my bad, thanks for the fix @coalman321!!

**Comment by coalman321** [comment]
All good! Thanks for getting this fix back into mainline. How long should we expect for it to hit the PPA's?

**Pull request merged**
